name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: adracea/gha-sbomb-merge@main
        with:
          files: "./tests/bom*.xml"
          cdxversion: "1.3"
          ofile: "./tests/finalBom.xml"
      - name: Check outputs and modified files
        run: |
                    test "${{ steps.selftest.outputs.success }}" == "./tests/finalBom.xml"